apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - voting.home-lab.webdemoapp.com
      secretName: voting-tls
  rules:
    - host: voting.home-lab.webdemoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting
                port:
                  number: 8080
