apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftista-dev
resources:
  - ../../../base/voting
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: 8060633493/craftista-voting
    newTag: latest
replicas:
  - name: voting
    count: 1
