apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftista-dev
resources:
  - ../../../base/voting
images:
  - name: 8060633493/craftista-voting
    newTag: postgres
replicas:
  - name: voting
    count: 1
