apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
data:
  SPRING_PROFILES_ACTIVE: "production"
  DATABASE_MAX_CONNECTIONS: "20"
  LOG_LEVEL: "WARNING"
  CATALOGUE_SERVICE_URL: "http://catalogue.craftista-prod.svc.cluster.local:5000/api/products"
  APP_VERSION: "1.0.0"
