apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - voting.webdemoapp.com
      secretName: voting-prod-tls
  rules:
    - host: voting.webdemoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting
                port:
                  number: 8080
