apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogue
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - catalogue.webdemoapp.com
      secretName: catalogue-prod-tls
  rules:
    - host: catalogue.webdemoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catalogue
                port:
                  number: 5000
