apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/craftista/dev/voting/config"
    spec:
      containers:
        - name: voting
          image: 8060633493/craftista-voting:dev-latest
          livenessProbe:
            initialDelaySeconds: 600
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            initialDelaySeconds: 600
            periodSeconds: 10
            failureThreshold: 3
