apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting
spec:
  tls:
    - hosts:
        - voting.home-lab.webdemoapp.com
      secretName: voting-dev-tls
  rules:
    - host: voting.home-lab.webdemoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting
                port:
                  number: 8080
