apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - ../../../../base/voting

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: voting
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: voting
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: voting-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: voting

replicas:
  - name: voting
    count: 1

images:
raftista-voting/,/newTag:/ s/newTag:.*/newTag: develop-f1d1a48c846f5c03ddba7c4f52e9a14d4afcbd20/
    newTag: develop-a37fb46fc3eea2450e2c5844214b4d4e2690aa2c
