apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - ../../../../base/voting

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: voting
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: voting
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: voting-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: voting

replicas:
  - name: voting
    count: 1

images:
  - name: 8060633493/craftista-voting
    newTag: develop-a911a8cb2698b5817d6395cab388bc271d1b9693
raftista-voting/,/newTag:/ s/newTag:.*/newTag: develop-56c29236784cb42352dc0d88eb9f8460fb02d9ae/
    newTag: develop-6f8b00690d4a41b11d9ed4501a6e1fdc737bf5ea
raftista-voting/,/newTag:/ s/newTag:.*/newTag: develop-e1e39573c699d5bae18ff4cc9cc5b095e02ff95b/
    newTag: develop-d70ab86775f0ef242a18b9e1ca3786d7cc31d08d
raftista-voting/,/newTag:/ s/newTag:.*/newTag: develop-f1d1a48c846f5c03ddba7c4f52e9a14d4afcbd20/
    newTag: develop-a37fb46fc3eea2450e2c5844214b4d4e2690aa2c
