- op: replace
  path: /spec/template/spec/containers/0/image
  value: 8060633493/craftista-voting:develop-b6103ceb8f51ee5f2a16d4f169abc4309b1e5466
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 50m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 128Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 200m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 256Mi
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
  value: 180
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
  value: 180
- op: add
  path: /spec/template/metadata/labels/environment
  value: dev
- op: add
  path: /spec/template/metadata/labels/managed-by
  value: kustomize
- op: add
  path: /spec/template/metadata/labels/app
  value: craftista-voting
