apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftista-dev
resources:
  - ../../../base/catalogue
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: 8060633493/craftista-catalogue
    newTag: latest
replicas:
  - name: catalogue
    count: 1
