apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-prod

resources:
  - namespace.yaml
  - vault-ca.yaml
  - frontend
  - catalogue
  - voting
  - recommendation
  - vault-tls

commonLabels:
  environment: prod
