apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftista-dev
resources:
  - ../../../base/deps/mongodb
  - ../../../base/deps/postgres
  - ../../../base/deps/redis
patches:
  - target:
      kind: StatefulSet
    patch: |
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: nfs-csi
  - target:
      kind: PersistentVolumeClaim
    patch: |
      - op: add
        path: /spec/storageClassName
        value: nfs-csi