apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - service-canary.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app: catalogue
  managed-by: kustomize
