apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendation
spec:
  tls:
    - hosts:
        - recommendation.staging.webdemoapp.com
      secretName: recommendation-staging-tls
  rules:
    - host: recommendation.staging.webdemoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recommendation
                port:
                  number: 8080
