apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DATABASE_MAX_CONNECTIONS: "5"
  LOG_LEVEL: "DEBUG"
  CATALOGUE_SERVICE_URL: "http://catalogue.craftista-dev.svc.cluster.local:5000/api/products"
  APP_VERSION: "1.0.0-dev"
