apiVersion: v2
name: voting
description: Craftista Voting Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - craftista
  - voting
  - java
  - spring-boot
maintainers:
  - name: Obinna Iheanacho
    email: Iheanachocharlie@gmail.com
