replicaCount: 1

image:
  tag: "develop-54132bf0fa29b2743d06477675201f0831712b43"

ingress:
  hosts:
    - host: voting.dev.webdemoapp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: voting-dev-tls
      hosts:
        - voting.dev.webdemoapp.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: development
  - name: CATALOGUE_SERVICE_URL
    value: http://catalogue:5000/api/products
  - name: CATALOGUE_SYNC_INTERVAL
    value: "60000"
  - name: LOG_LEVEL
    value: DEBUG
  - name: JPA_DDL_AUTO
    value: update
  - name: JPA_SHOW_SQL
    value: "true"

postgresql:
  enabled: true
  host: "" # Injected from Vault
  port: 5432
  database: voting
  username: "" # Injected from Vault
  password: "" # Injected from Vault

migration:
  enabled: true
  image:
    tag: "develop-54132bf0fa29b2743d06477675201f0831712b43"

vault:
  enabled: true
  role: voting
  secretPath: secret/data/craftista/dev/voting
