apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - ../../../../base/catalogue

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: catalogue
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: catalogue
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: catalogue-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: catalogue

replicas:
  - name: catalogue
    count: 1

images:
raftista-catalogue/,/newTag:/ s/newTag:.*/newTag: develop-79620eb06cc56dfd7ed2c329909f1a91d88372a3/
    newTag: develop-0ff4666393fbb64fe51557ac1767aaffbf472007
