apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-staging

resources:
  - ../../../../base/frontend

commonLabels:
  environment: staging

patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: frontend
  - path: service-patch.yaml
    target:
      kind: Service
      name: frontend
  - path: service-patch.yaml
    target:
      kind: Service
      name: frontend-canary
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: frontend-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: frontend
