apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - ../../../../base/frontend

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: frontend-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: frontend

replicas:
  - name: frontend
    count: 1
