replicaCount: 1

image:
  tag: "develop-33de9da5dfae9b3d81ecac83bade6d319fd6f517"

ingress:
  hosts:
    - host: recommendation.dev.webdemoapp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: recommendation-dev-tls
      hosts:
        - recommendation.dev.webdemoapp.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

env:
  - name: GIN_MODE
    value: debug
  - name: LOG_LEVEL
    value: DEBUG

redis:
  enabled: true
  host: "" # Injected from Vault
  port: 6379
  password: "" # Injected from Vault
  database: 0

vault:
  enabled: true
  role: recommendation
  secretPath: secret/data/craftista/dev/recommendation
