replicaCount: 3

image:
  tag: "prod-latest"

ingress:
  hosts:
    - host: recommendation.webdemoapp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: recommendation-prod-tls
      hosts:
        - recommendation.webdemoapp.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: GIN_MODE
    value: release
  - name: LOG_LEVEL
    value: WARN

redis:
  enabled: true
  host: "" # Injected from Vault
  port: 6379
  password: "" # Injected from Vault
  database: 0

vault:
  enabled: true
  role: recommendation
  secretPath: secret/data/craftista/prod/recommendation
