apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../../base
  - cloudflare-external-secret.yaml

patches:
  - path: secret-store-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      component: cert-manager-secrets