apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - namespace.yaml
  - vault-ca.yaml
  - frontend
  - catalogue
  - voting
  - recommendation

commonLabels:
  environment: dev
