apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: craftista-dev
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrjCCApagAwIBAgIUd2wp5e0u4kKF+R+hSZ7oiV4YPkwwDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBUxvY2FsMRAwDgYDVQQHEwdIb21l
    bGFiMRAwDgYDVQQKEwdIb21lbGFiMREwDwYDVQQLEwhWYXVsdCBDQTEZMBcGA1UE
    AxMQSG9tZWxhYiBWYXVsdCBDQTAeFw0yNjAyMDYwODI5MDBaFw0zMTAyMDUwODI5
    MDBaMG8xCzAJBgNVBAYTAlVTMQ4wDAYDVQQIEwVMb2NhbDEQMA4GA1UEBxMHSG9t
    ZWxhYjEQMA4GA1UEChMHSG9tZWxhYjERMA8GA1UECxMIVmF1bHQgQ0ExGTAXBgNV
    BAMTEEhvbWVsYWIgVmF1bHQgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDRHXL5bTVlezRBNkfiWFcCjxQOjbEKBjSoAuntrf8keVcAxd0zvi+uIEYb
    W98DqXDmdrekIJKWOJpyx0EBMhNgAFJ3uuGOftK+u5cGgphEIrN6sM926Tj/I85N
    Do0YQdoy8wiePJS/MdPXgsUhKnjxf3pZfUipGYUGFx/gjFiswKzQxQOJ+BE5w3ZT
    BXtt/WHMgePYr3j7HdumcJ6njuJ2VgzmsIAb4Cb/16gcWtOZh4DLuebNfYQ249IF
    yvwQmQUxmIkPr5yQOWzAPkeJanFoiJd2heloWgxvbD5D2Bvc/RDWZeDz4cxXDNqT
    G+qHSjksyH4xR+k5f4Hls7AvZPJrAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTopGkGQ9JpJSgcTaCpfBg2H6VFljAN
    BgkqhkiG9w0BAQsFAAOCAQEAxVGRJ8LEDV9BLjzXKGGyDtnqlAhVo+utc0dUPztZ
    vS/638xTwGdZlpp4Kin2DOvP7XBOvbxv9mNbK3yiVM51BNv2RFf1v1RzKBFmmyTl
    E5tqq96pvLB4Avio2totezpUeg19iH3nJwmR9qJLt3OKOP3h8wWbhFHLffn3JbD6
    4pmVcyWDRAmoNuoX5qwMrkWsO7OghqHJDaELd+y+4ThNcDA421EU0SgNwVffxThC
    PopuN68irFOUzbPPWrNpDFrwLIS221gvnV4StG102L7Tg8+sZDGwbpfkEOQ+HVhG
    RZWyQ0zjHm4LvBShwV+KAfv7CVtlE+wkdBdnfkQJs6YOvQ==
    -----END CERTIFICATE-----