apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-staging

resources:
  - ../../../base
  - catalogue-secrets.yaml
  - catalogue-mongodb-secret.yaml
  - frontend-secrets.yaml
  - recommendation-secrets.yaml
  - recommendation-redis-secret.yaml
  - voting-secrets.yaml
  - voting-postgres-secret.yaml
  - mongodb-secrets.yaml
  - postgres-secrets.yaml
  - redis-secrets.yaml
  - dockerhub-pull-secret.yaml

patches:
  - path: secret-store-patch.yaml
  

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      environment: staging

