apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/craftista/staging/voting/config"
    spec:
      containers:
        - name: voting
          image: 8060633493/craftista-voting:staging-latest
