apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftista-dev
resources:
  - ../../../base/frontend
images:
  - name: 8060633493/craftista-frontend
    newTag: latest
replicas:
  - name: frontend
    count: 1
