apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalogue
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/craftista/staging/catalogue/config"
    spec:
      containers:
        - name: catalogue
          image: 8060633493/craftista-catalogue:staging-latest
