apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-staging

resources:
  - ../../../../base/catalogue

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml
    target:
      kind: Rollout
      name: catalogue
  - path: resources-patch.yaml
    target:
      kind: Rollout
      name: catalogue
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: catalogue-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: catalogue

images:
  - name: 8060633493/craftista-catalogue
    newTag: dev-latest
