- op: replace
  path: /spec/template/spec/containers/0/image
  value: 8060633493/craftista-catalogue:dev-latest
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 100m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 128Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 400m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 512Mi
- op: add
  path: /spec/template/metadata/labels/environment
  value: staging
- op: add
  path: /spec/template/metadata/labels/managed-by
  value: kustomize
- op: add
  path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-config
  value: secret/data/craftista/staging/catalogue/config
