apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "version": "{{ .Chart.AppVersion }}",
      "productsApiBaseUri": "{{ (index .Values.env 2).value }}",
      "recommendationBaseUri": "{{ (index .Values.env 3).value }}",
      "votingBaseUri": "{{ (index .Values.env 4).value }}"
    }
