apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recommendation.fullname" . }}-config
  labels:
    {{- include "recommendation.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "version": "{{ .Chart.AppVersion }}"
    }
