apiVersion: v2
name: frontend
description: Craftista Frontend Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - craftista
  - frontend
  - nodejs
  - express
maintainers:
  - name: Obinna Iheanacho  
    email: Iheanachocharlie@gmail.com
