apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-dev

resources:
  - ../../../../base/recommendation

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: recommendation
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: recommendation
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: recommendation-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: recommendation

replicas:
  - name: recommendation
    count: 1

images:
raftista-recommendation/,/newTag:/ s/newTag:.*/newTag: develop-33de9da5dfae9b3d81ecac83bade6d319fd6f517/
    newTag: develop-1060d4d5a1c92c51976dfdb2b7fa52b4d2eb66c9
