apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  labels:
    app: voting
data:
  SPRING_PROFILES_ACTIVE: "production"
  DATABASE_MAX_CONNECTIONS: "10"
  LOG_LEVEL: "INFO"
  CATALOGUE_SERVICE_URL: "http://catalogue:5000/api/products"
  CATALOGUE_SERVICEURL: "http://catalogue:5000/api/products"
  APP_VERSION: "1.0.0"
