apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting
  labels:
    app: voting
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - voting.DOMAIN_PLACEHOLDER
      secretName: voting-tls
  rules:
    - host: voting.DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting
                port:
                  number: 8080
