apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rollout.yaml
  - service.yaml
  - service-canary.yaml
  - configmap.yaml
  - ingress.yaml
  - migration-job.yaml

commonLabels:
  app: voting
  managed-by: kustomize
