apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftista-prod

resources:
  - ../../../base
  - catalogue-secrets.yaml
  - frontend-secrets.yaml
  - recommendation-secrets.yaml
  - voting-secrets.yaml
  - dockerhub-pull-secret.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  environment: prod
