apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
data:
  SPRING_PROFILES_ACTIVE: "staging"
  DATABASE_MAX_CONNECTIONS: "10"
  LOG_LEVEL: "INFO"
  CATALOGUE_SERVICE_URL: "http://catalogue.craftista-staging.svc.cluster.local:5000/api/products"
  APP_VERSION: "1.0.0-staging"
